document.getElementById('add-money-button').addEventListener('click',function(){
showSectionById('add-money-form')
})
document.getElementById('cash-out-money-button').addEventListener('click',function(){
    showSectionById('cash-out-form')
    })
    document.getElementById('Transfer-Money-button').addEventListener('click',function(){
        showSectionById('Transfer-Money-form')
        })
        document.getElementById('Get-Bonus-button').addEventListener('click',function(){
            showSectionById('Get-Bonus-form')
            })
            document.getElementById('Pay-Bill-button').addEventListener('click',function(){
                showSectionById('Pay-Bill-form')
                })
                document.getElementById('Transaction-button').addEventListener('click',function(){
                    showSectionById('Transaction-form')
                    })
                  